
CREATE TABLE COMPANY
(
  ID      VARCHAR(200) NOT NULL COMMENT 'uniqu id',
  NAME    VARCHAR(200) NOT NULL COMMENT '이름',
  AGE     INT          NULL     COMMENT '나이',
  ADDRESS VARCHAR(200) NULL     COMMENT '주소',
  SALARY  INT          NOT NULL COMMENT '월급',
  PRIMARY KEY (ID)
) COMMENT '회사 구성원';

CREATE TABLE DEPARTMENT
(
  ID     VARCHAR(200) NOT NULL COMMENT 'uniqu id',
  DEPT   VARCHAR(200) NOT NULL COMMENT '부서',
  EMP_ID VARCHAR(200) NOT NULL COMMENT 'uniqu id',
  PRIMARY KEY (EMP_ID)
) COMMENT '부서명들';

ALTER TABLE DEPARTMENT
  ADD CONSTRAINT FK_COMPANY_TO_DEPARTMENT
    FOREIGN KEY (ID)
    REFERENCES COMPANY (ID);
